# Generated by Django 4.2 on 2023-05-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondeeh1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='continente',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='lingua',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='moeda',
        ),
        migrations.AddField(
            model_name='pais',
            name='chutes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
