# Generated by Django 4.2 on 2023-05-31 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ondeeh1', '0006_alter_usuario_user_alter_usuario_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together=set(),
        ),
    ]
